services:
  # app:
  #   image: my-backend-image:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: my-backend-container
  #   restart: always
  #   env_file: .env
  #   # Это гарантирует, что app начнет запуск только ПОСЛЕ успешного healthcheck базы
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app
  #     # Если uv создает какие-то локальные папки в /app, которые не нужны на хосте:
  #     # - /app/.venv 
  #   networks:
  #     - backend_network
  #   environment:
  #     - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}

  database:
    image: postgres:17
    container_name: database
    restart: always
    env_file: .env 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5436:5432"
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s   # Ускорим проверку для старта
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_quiz:/var/lib/postgresql/data

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data_quiz: